media:
    input: src/media
    output: ../../media

content:
    - name: artists
      label: Artists
      type: collection
      path: 'src/content/artists'
      filename: '{primary}.md'
      view:
          fields: [title, hidden]
      fields:
          - name: hidden
            label: Hidden
            type: boolean
            default: false
          - name: title
            label: Title
            type: string
          - name: featuredImage
            label: Featured Image
            type: image
            required: false
          - name: body
            label: Biography
            type: rich-text
          - name : summary
            label: Summary
            type: rich-text
            required: false
          - name: works
            label: Works
            type: object
            required: false
            list:
              collapsible:
                collapsed: true
                summary: "{fields.title} ( {fields.year} ) #{fields.inventorynumber}"
            fields:
                - name: src
                  label: Image
                  type: image
                - name: title
                  label: Title
                  type: string
                  required: false
                - name: year
                  label: Year
                  type: date
                  options:
                    format: 'yyyy'
                  required: false
                - name: category
                  label: Category
                  type: string
                  required: false
                - name: inventorynumber
                  label: Catalog Number
                  type: string
                  required: false
                - name: info
                  label: Description
                  type: text
                  required: false
                - name: credit
                  label: Copyright 
                  type: text 
                  required: false
                # - name: copyright
                #   label: Copyright
                #   type: text
          - name: resources
            label: Resources
            type: file
            required: false
            multiple: true
    - name: rooms
      label: Rooms
      type: collection
      path: 'src/content/rooms'
      filename: '{primary}.md'
      view:
          fields: [title, startdate, enddate, venue, hidden]
      fields:
          - name: title
            label: Title
            type: string
          - name: hidden
            label: Hidden
            type: boolean
            default: false
          - name: startdate
            label: Start
            type: date
            options:
              format: 'yyyy-MM-dd'
            required: true
          - name: enddate
            label: End (set next if no ending date)
            type: date
            options:
              format: 'yyyy-MM-dd'
            required: true
          - name: ongoing
            label: Open ended
            type: boolean
            default: false
          - name : priority
            label : Priority 
            type : number 
            required : false 
            default : 0 
          - name : artists 
            label : Artists 
            type : reference
            options:
              collection : artists 
              multiple : true 
              search : [title] 
              value : "{primary}" 
              label : "{title}"
              image: "{featuredImage}" 
          - name : venue 
            label : Venue 
            type: reference
            options:
              collection : venues 
              search : [title, town] 
              value : "{primary}" 
              label : "{title}"
              image: "{featuredImage}"

          - name: body
            label: About
            type: rich-text
            required: false
          - name: images
            label: Images
            type: image
            required: false
            multiple: true
    - name: venues
      label: Venues
      type: collection
      path: 'src/content/venues'
      filename: '{primary}.md'
      view:
          fields: [title, town, hidden]
      fields:
          - name: title
            label: Title
            type: string
          - name: hidden
            label: Hidden
            type: boolean
            default: false
          - name: town
            label: Town
            type: string
          - name: address
            label: Address
            type: string
            required: false
          - name: map
            label: Map Link
            type: string
            required: false
          - name: geo
            label: Map
            type: map
            required: false
          - name: plus_code
            label: Pluscode
            type: string
            required: false
          - name: lat
            label: Latitude
            type: number
            required: false
          - name: lon
            label: Longitude
            type: number
            required: false
          - name: body
            label: About
            type: rich-text
            required: false
          - name: images
            label: Images
            type: image
            required: false
            multiple: true
    - name: films
      label: Films
      type: collection
      path: 'src/content/films'
      filename: '{primary}.md'
      view:
          fields: [title, hidden]
      fields:
          - name: title
            label: Title
            type: string
          - name: hidden
            label: Hidden
            type: boolean
            default: false
          - name: url
            label: Url
            type: string
          - name: artists
            label: Artists
            type: reference
            options:
              collection : artists 
              multiple : true 
              search : [title] 
              value : "{primary}" 
              label : "{title}"
              image: "{featuredImage}" 
          - name: body
            label: About
            type: rich-text
            required: false

  # - label: "Venues"
  #   label_singular: "Venue"
  #   name: "venues"
  #   folder: "src/content/venues"
  #   create: true
  #   summary_fields: ["title","town"]
  #   editor:
  #     preview: false
  #   fields:
  #     - { label: "Venue", name: "title", widget: "string" }
  #     - { label: "Hidden", name: "hidden", widget: "boolean", default: false }
  #     - { label: "Town", name: "town", widget: "string" }
  #     - { label: "Address", name: "address", widget: "string", required: false }
  #     - { label: "Map Link", name: "map", widget: "string", required: false }
  #     - { label: "Map", name: "geo", widget: "map", required: false }
  #     - { label: "Pluscode", name: "plus_code", widget: "string", required: false }
  #     # - { label: "Latitude", name: "lat", widget: "number", required: false }
  #     # - { label: "Longitude", name: "lon", widget: "number", required: false }      
  #     - { label: "About", name: "body", widget: "markdown", required: false }
  
  # - label: "Films"
  #   label_singular: "Film"
  #   name: "films"
  #   editor:
  #     preview: false
  #   folder: "src/content/films"
  #   create: true
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Hidden", name: "hidden", widget: "boolean", default: false }
  #     - { label: "Url", name: "url", widget: "string" }
  #     - label: "Artists"
  #       name: "artists"
  #       widget: "relation"
  #       collection: "artists"
  #       multiple: true
  #       search_fields: ["title"]
  #       value_field: "{{slug}}"
  #       display_fields: ["title"]
  #       required: false     