backend:
    name: github
    repo: mimecine/ar-new
    branch: master # Branch to update (optional; defaults to master)
    base_url: https://cms-auth.mimecom.workers.dev/


media_folder: "src/media"

media_libraries:
  stock_assets:
    providers: []

# #static cms
media_library:
  max_file_size: 1000000000

site_url: https://artistrooms.netlify.app
display_url: https://artistrooms.netlify.app
logo_url: https://artistrooms.netlify.app/favicon.svg


# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:

  - label: "Artists"
    label_singular: "Artist"
    name: "artists"
    folder: "src/content/artists"
    create: true
    summary: "{{fields.title}} {{ fields.hidden | ternary(' (HIDDEN)','') }}"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Hidden", name: "hidden", widget: "boolean", default: false }
      - { label: "Biography", name: "body", widget: "markdown" }
      - { label: "Summary", name: "summary", widget: "markdown", required: false }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - label: "Works"
        label_singular: "Work"
        name: "works"
        widget: "list"
        required: false
        summary: "{{fields.inventorynumber}} : {{fields.title}}"
        fields: 
          - { label: Image, name: src, widget: image }
          - { label: Title, name: title, widget: string, required: false }
          - { label: Year, name: year, widget: "datetime", time_format: false, format: 'yyyy', required: false }
          - { label: Category, name: category, widget: string, required: false }
          - { label: "Catalog Number", name: inventorynumber, widget: string, required: false }
          - { label: "Description", name: "info", widget: "string", required: false }
          - { label: "Copyright", name: "credit", widget: "string", required: false }
      - label: "Resources"
        label_singular: "Resource"
        name: "resources"
        widget: "list"
        required: false
        fields:
          - { label: "File", name: "path", widget: "file" }
          - { label: "Title", name: "title", widget: "string" }
          
 
  - label: "Rooms"
    label_singular: "Room"
    name: "rooms"
    folder: "src/content/rooms"
    create: true
    summary: "{{title}} {{startdate }} @ {{venue | upper}}  {{hidden | ternary('---**HIDDEN**', '')}}"
    sortable_fields: 
      fields: ["title","venue","startdate","enddate","hidden"]
      default:
        field: "enddate"
        direction: Descending

    editor:
      preview: false
    thumbnail: "images.*.src"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Hidden", name: "hidden", widget: "boolean", default: false }
      - { label: "Start", name: "startdate", widget: "datetime", date_format: 'yyyy-MM-dd', time_format: false, format: 'yyyy-MM-dd', required: true}
      - { label: "End (set next if no ending date)", name: "enddate", widget: "datetime", date_format: 'yyyy-MM-dd', time_format: false, format: 'yyyy-MM-dd', required: true}
      - { label: "Open ended", name: "ongoing", widget: "boolean", default: false }
      - { label: "Priority", name: "priority", widget: "number", required: false, default: 0 }
      - label: "Artists"
        name: "artists"
        widget: "relation"
        collection: "artists"
        multiple: true
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
      - label: "Venue"
        name: "venue"
        widget: "relation"
        collection: "venues"
        search_fields: ["title", "town"]
        value_field: "{{slug}}"
        display_fields: ["title", "town"]
      - { label: "About", name: "body", widget: "markdown", required: false }
      - label: "Images"
        label_singular: "Image"
        name: "images"
        widget: "list"
        required: false
        summary: "{{fields.title}}"
        fields: 
          - { label: Image, name: src, widget: image }
          - { label: Title, name: title, widget: string, required: false }
          - {label: Alt, name: alt, widget: string, required: false }
          - { label: Caption, name: caption, widget: string, required: false }
          - { label: "Credit", name: "credit", widget: "text", required: false }
          - { label: "Copyright", name: "copyright", widget: "text", required: false }
      - label: "Videos"
        label_singular: "Video"
        name: "videos"
        widget: "list"
        required: false
        summary: "{{fields.title}}"
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - { label: Description, name: description, widget: string, required: false }
          - { label: Video Link, name: src, widget: string, required: true }
          - { label: Poster Image, name: poster, widget: image, required: false }
          - { label: "Credit", name: "credit", widget: "text", required: false }
          - { label: "Copyright", name: "copyright", widget: "text", required: false }


  - label: "Venues"
    label_singular: "Venue"
    name: "venues"
    folder: "src/content/venues"
    create: true
    summary_fields: ["title","town"]
    editor:
      preview: false
    fields:
      - { label: "Venue", name: "title", widget: "string" }
      - { label: "Hidden", name: "hidden", widget: "boolean", default: false }
      - { label: "Town", name: "town", widget: "string" }
      - { label: "Address", name: "address", widget: "string", required: false }
      - { label: "Map Link", name: "map", widget: "string", required: false }
      - { label: "Map", name: "geo", widget: "map", required: false }
      - { label: "Pluscode", name: "plus_code", widget: "string", required: false }
      # - { label: "Latitude", name: "lat", widget: "number", required: false }
      # - { label: "Longitude", name: "lon", widget: "number", required: false }      
      - { label: "About", name: "body", widget: "markdown", required: false }
  
  - label: "Films"
    label_singular: "Film"
    name: "films"
    editor:
      preview: false
    folder: "src/content/films"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Hidden", name: "hidden", widget: "boolean", default: false }
      - { label: "Url", name: "url", widget: "string" }
      - { label: "Poster Image", name: "poster", widget: "string", required: false }
      - label: "Artists"
        name: "artists"
        widget: "relation"
        collection: "artists"
        multiple: true
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        required: false     

  - name: 'news'
    label: 'News (not implemented)'
    label_singular: 'Article'
    folder: 'src/content/news'
    create: true
    summary: "{{title | upper}} | {{date | date('YYYY-MM-DD')}} | {{body | truncate(20, '***')}} {{ hidden | ternary(' (HIDDEN)', '') }}"
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'hidden', widget: 'boolean' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: "Pages"
    label_singular: "Page"
    name: "pages"
    preview_path: "{{slug}}"
    folder: "src/pages"
    public_folder: ../media
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "../layouts/Page.astro"}
      - { label: "Hidden", name: "hidden", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Artists"
        name: "artists"
        widget: "relation"
        collection: "artists"
        multiple: true
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        required: false
      - label: "Rooms"
        name: "rooms"
        widget: "relation"
        collection: "rooms"
        multiple: true
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        required: false
          

  - label: "Site Settings"
    name: "settings"
    editor:
      preview: false
    files:
    - label: "Homepage Settings"
      name: "index_settings"
      file: "src/_data/index_settings.json"
      fields:
      - label: Intro
        name: intro
        widget: markdown
        required: false
      - label: "Featured Rooms"
        name: "rooms"
        widget: "relation"
        collection: "rooms"
        search_fields: ["title","town"]
        value_field: "{{slug}}"
        display_fields: ["title","town"]
        multiple: true
        required: false
      - label: "Featured Artists"
        name: "artists"
        widget: "relation"
        collection: "artists"
        multiple: true
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        required: false
      - label: "Featured Films"
        name: "films"
        widget: "relation"
        collection: "films"
        multiple: true
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        required: false
      - label: Outro
        name: outro
        widget: markdown
        required: false

    - label: "Rooms Page Settings"
      name: "rooms_settings"
      file: "src/_data/rooms_settings.json"
      fields:
      - label: Intro
        name: intro
        widget: markdown
        required: false
      - label: "Featured Rooms"
        name: "rooms"
        widget: "relation"
        collection: "rooms"
        search_fields: ["title","town"]
        value_field: "{{slug}}"
        display_fields: ["title","town"]
        multiple: true
        required: false
      - label: Outro
        name: outro
        widget: markdown
        required: false
    - label: "Artists Page Settings"
      name: "artists_settings"
      file: "src/_data/artists_settings.json"
      fields:
      - label: Intro
        name: intro
        widget: markdown
        required: false
      - label: "Featured Artists"
        name: "artists"
        widget: "relation"
        collection: "artists"
        multiple: true
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        required: false
      - label: Outro
        name: outro
        widget: markdown
        required: false
    - label: "Films Page Settings"
      name: "films_settings"
      file: "src/_data/films_settings.json"
      fields:
      - label: Intro
        name: intro
        widget: markdown
        required: false
      - label: "Featured Films"
        name: "films"
        widget: "relation"
        collection: "films"
        multiple: true
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        required: false
      - label: Outro
        name: outro
        widget: markdown
        required: false
    - label: "Links"
      name: "links"
      file: "src/_data/links.yml"
      fields:
        - label: "Nav Items - Not Implemented"
          name: links
          widget: list
          collapsed: false
          fields:
            - { label: Title, name: title, widget: string }
            - { label: URL, name: url, widget: string }
            - { label: Description, name: desc, widget: string, required: false }
    - label: "Meta Settings"
      name: "settings"
      file: "src/_data/meta_settings.json"
      fields:
        - { label: Name, name: name, widget: string }
        - { label: Author, name: author, widget: string }
        - { label: URL, name: url, widget: string }
