backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/media"
# public_folder: "/media"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:

  - label: "Artists"
    label_singular: "Artist"
    name: "artists"
    folder: "src/content/artists"
    create: true
    editor:
      preview: false
    identifier_field: "name"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Biography", name: "body", widget: "markdown" }
      - label: "Works"
        name: "works"
        widget: "list"
        required: false
        summary: "{{fields.image}}"
        fields: 
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: "Catalog Number", name: id, widget: string }
          - { label: "Description", name: "description", widget: "markdown" }
  - label: "Rooms"
    label_singular: "Room"
    name: "rooms"
    folder: "src/content/rooms"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Start", name: "start", widget: "datetime", date_format: 'dd.MM.yyyy', time_format: false, format: 'yyyy-MM-dd'}
      - { label: "End", name: "end", widget: "datetime", date_format: 'dd.MM.yyyy', time_format: false, format: 'yyyy-MM-dd'}
      - label: "Artists"
        name: "artists"
        widget: "relation"
        collection: "artists"
        multiple: true
        search_fields: ["name"]
        value_field: "{{slug}}"
        display_fields: ["name"]
      - label: "Venue"
        name: "venue"
        widget: "relation"
        collection: "venues"
        search_fields: ["title", "town"]
        value_field: "title"
        display_fields: ["title", "town"]
      - { label: "About", name: "body", widget: "markdown", required: false }
      - label: "Photos"
        label_singular: "Photo"
        name: "photos"
        widget: "list"
        required: false
        field: { label: Image, name: image, widget: image }

  - label: "Venues"
    label_singular: "Venue"
    name: "venues"
    folder: "src/content/venues"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Venue", name: "title", widget: "string" }
      - { label: "Town", name: "town", widget: "string" }
      - { label: "About", name: "body", widget: "markdown", required: false }

  - label: "Works"
    label_singular: "Work"
    name: "works"
    folder: "src/content/works"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Links"
        name: "links"
        file: "src/_data/links.json"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.json"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
